DROP DATABASE IF EXISTS exampledb;
CREATE DATABASE exampledb;

DROP DATABASE IF EXISTS testdb;
CREATE DATABASE testdb;

-- utilities admin db --

DROP DATABASE IF EXISTS utils_db;

CREATE DATABASE utils_db;

USE utils_db;

CREATE TABLE utilities (id INT NOT NULL AUTO_INCREMENT, type VARCHAR(30) NOT NULL, name VARCHAR(100) NOT NULL, url VARCHAR(500),  logo VARCHAR (500), PRIMARY KEY (id));